import {Router} from 'express';
import mongoose from 'mongoose';
import {Plant,WateringLog,FertilizerLog,HealthRecord,GrowthRecord} from '../models/index.js';
import {careFor,careMap} from '../services/care.js';
const r=Router();
const models={watering:WateringLog,fertilizer:FertilizerLog,health:HealthRecord,growth:GrowthRecord};
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const validId=(id)=>{if(!mongoose.isValidObjectId(id)){const e=new Error('Invalid record id');e.status=400;throw e;}};
r.get('/plants',asyncRoute(async(req,res)=>{const q={};if(req.query.type)q.plantType=req.query.type;if(req.query.environment)q.indoorOutdoor=req.query.environment;if(req.query.sunlight)q.sunlightRequirement={$regex:req.query.sunlight,$options:'i'};const sort=req.query.sort==='newest'?{dateAdded:-1}:req.query.sort==='oldest'?{dateAdded:1}:{name:1};let items=await Plant.find(q).sort(sort);if(req.query.search){const s=req.query.search.toLowerCase();items=items.filter(p=>`${p.name} ${p.scientificName} ${p.location}`.toLowerCase().includes(s));}const care=await careMap(items);if(req.query.status)items=items.filter(p=>care[p.id]?.status===req.query.status);res.json(items.map(p=>({...p.toObject(),care:care[p.id]})));}));
r.post('/plants',asyncRoute(async(req,res)=>{const p=await Plant.create(req.body);res.status(201).json(p);}));
r.get('/plants/:id',asyncRoute(async(req,res)=>{validId(req.params.id);const p=await Plant.findById(req.params.id);if(!p){const e=new Error('Plant not found');e.status=404;throw e;}const [care,watering,fertilizer,health,growth]=await Promise.all([careFor(p),WateringLog.find({plantId:p.id}).sort({date:-1}),FertilizerLog.find({plantId:p.id}).sort({dateApplied:-1}),HealthRecord.find({plantId:p.id}).sort({detectedDate:-1}),GrowthRecord.find({plantId:p.id}).sort({date:1})]);res.json({plant:p,care,watering,fertilizer,health,growth});}));
r.put('/plants/:id',asyncRoute(async(req,res)=>{validId(req.params.id);const p=await Plant.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!p){const e=new Error('Plant not found');e.status=404;throw e;}res.json(p);}));
r.delete('/plants/:id',asyncRoute(async(req,res)=>{validId(req.params.id);const p=await Plant.findByIdAndDelete(req.params.id);if(!p){const e=new Error('Plant not found');e.status=404;throw e;}await Promise.all(Object.values(models).map(M=>M.deleteMany({plantId:p._id})));res.json({deleted:true,id:p.id});}));
for(const [key,M] of Object.entries(models)){
 r.get('/'+key,asyncRoute(async(req,res)=>{const q={};if(req.query.plantId)q.plantId=req.query.plantId;if(req.query.from||req.query.to){const field=key==='fertilizer'?'dateApplied':key==='health'?'detectedDate':'date';q[field]={};if(req.query.from)q[field].$gte=new Date(req.query.from);if(req.query.to){const end=new Date(req.query.to);end.setHours(23,59,59,999);q[field].$lte=end;}}if(req.query.type&&key==='health')q.issueType=req.query.type;res.json(await M.find(q).populate('plantId','name').sort({createdAt:-1}));}));
 r.post('/'+key,asyncRoute(async(req,res)=>{if(!mongoose.isValidObjectId(req.body.plantId)){const e=new Error('A valid plantId is required');e.status=400;throw e;}if(!await Plant.exists({_id:req.body.plantId})){const e=new Error('Referenced plant does not exist');e.status=404;throw e;}const x=await M.create(req.body);res.status(201).json(await x.populate('plantId','name'));}));
 if(key==='health')r.put('/health/:id',asyncRoute(async(req,res)=>{validId(req.params.id);const x=await M.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!x){const e=new Error('Health record not found');e.status=404;throw e;}res.json(x);}));
 r.delete('/'+key+'/:id',asyncRoute(async(req,res)=>{validId(req.params.id);const x=await M.findByIdAndDelete(req.params.id);if(!x){const e=new Error('Record not found');e.status=404;throw e;}res.json({deleted:true,id:x.id});}));
}
r.get('/dashboard',asyncRoute(async(req,res)=>{const plants=await Plant.find().sort({name:1});const care=await careMap(plants);const records=await Promise.all(Object.entries(models).map(async([type,M])=>M.find().sort({createdAt:-1}).limit(12).populate('plantId','name').lean().then(rows=>rows.map(x=>({type,plant:x.plantId?.name||'Plant',date:x.date||x.dateApplied||x.detectedDate,summary:type==='watering'?`Watered · ${x.amount}`:type==='fertilizer'?`Fertilized · ${x.fertilizerName}`:type==='health'?`Health · ${x.issueType}`:`Growth · ${x.height??'—'} cm`,...x})))));const activity=records.flat().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,10);const growth=await GrowthRecord.find().sort({date:1}).populate('plantId','name').lean();const growthSnapshot=growth.slice(-30).map(x=>({date:x.date,plant:x.plantId?.name,height:x.height,leafCount:x.leafCount}));res.json({stats:{totalPlants:plants.length,wateringDue:Object.values(care).filter(c=>c.wateringDue).length,fertilizerDue:Object.values(care).filter(c=>c.nextFertilizer&&new Date(c.nextFertilizer)<=new Date(Date.now()+3*86400000)).length,activeHealthIssues:Object.values(care).reduce((a,c)=>a+c.activeHealthIssues,0)},plants:plants.map(p=>({...p.toObject(),care:care[p.id]})),care,activity,growthSnapshot});}));
r.get('/dashboard/stats',asyncRoute(async(req,res)=>res.json((await fetch(`http://127.0.0.1:${process.env.PORT||4000}/api/dashboard`).then(x=>x.json())).stats)));
r.get('/dashboard/care',asyncRoute(async(req,res)=>res.json(await careMap(await Plant.find()))));
r.get('/dashboard/activity',asyncRoute(async(req,res)=>{const d=await fetch(`http://127.0.0.1:${process.env.PORT||4000}/api/dashboard`).then(x=>x.json());res.json(d.activity);}));
export default r;
